### ISSUE TITLE
Assure DNS resolve is done only once

### ISSUE THREAD

**Issue by chadell** [dachad/tcpgoon#33]

**Comment by dcaba** [comment]
In order to test individual instances (closer to the mission of the project), this may have sense, but keeping the original mode with a flag could be an option. Any other rationale behind changing the mode?

**Comment by chadell** [comment]
my goal was just avoid resolving a DNS each TCP connection because the tcpgoon is only to stress TCP not DNS. So I would force this DNS caching  by default unless you have other ideas/suggestion on it

**Comment by chadell** [comment]
I've checked that it's only done once per execution. Not issue at all.

**Comment by dcaba** [comment]
Can you revisit this and provide more details about your tests? Please, use the binary generated by the compilation scripts/travis, or the docker image, rather than a "go run" or a direct "go build" in your machine, as the resolver may differ (we compile without cgo to avoid linking dynamically against libs, so it may mean your binary use the golang resolver, that behaves different)

**Comment by chadell** [comment]
@dcaba you were right,  using the binary I've checked and multiple DNS queries are generated...

**Comment by chadell** [comment]
https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by dcaba** [comment]
It'd be nice, but probably you will generate a binary dynamically linked against libc. So pure go looks the most portable option, but probably means using https://golang.org/pkg/net/#LookupIP before calling the Dial function (this is like the "most basic" discovery mechanism we will need to implement xD)

**Comment by chadell** [comment]
#51
